// user
export const USER_AUTH = "USER_AUTH";
export const USER_LOGOUT = " USER_LOGOUT";

// notes 
export const GET_NOTES_STARTED = "GET_NOTES_STARTED";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";
export const CREATE_NOTE_STARTED = "CREATE_NOTE_STARTED";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAILURE = "CREATE_NOTE_FAILURE";
export const CREATE_NOTE_SUCCESS_UPDATE_TEAM = "CREATE_NOTE_SUCCESS_UPDATE_TEAM";
export const DELETE_NOTE_STARTED = "DELETE_NOTE_STARTED";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILURE";
export const EDIT_NOTE_STARTED = "EDIT_NOTE_STARTED";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_FAILURE = "EDIT_NOTE_FAILURE";

// teams
export const GET_TEAMS_STARTED = "GET_TEAMS_STARTED";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAILURE = "GET_TEAMS_FAILURE";
export const GET_TEAMS_EXIST = "GET_TEAMS_EXIST";
export const CREATE_TEAM_STARTED = "CREATE_TEAM_STARTED";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILURE = "CREATE_TEAM_FAILURE";
export const DELETE_TEAM_STARTED = "DELETE_TEAM_STARTED";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILURE = "DELETE_TEAM_FAILURE";
