// user
export const USER_AUTH = "USER_AUTH";
export const USER_LOGOUT = " USER_LOGOUT";
export const INVITE_USER_STARTED = "INVITE_USER_STARTED";
export const INVITE_USER_SUCCESS = "INVITE_USER_SUCCESS";
export const INVITE_USER_FAILURE = "INVITE_USER_FAILURE";
export const ADD_USER_STARTED = "ADD_USER_STARTED";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";
export const REMOVE_USER_STARTED = "REMOVE_USER_STARTED";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAILURE = "REMOVE_USER_FAILURE";
export const PROMOTE_USER_STARTED = "PROMOTE_USER_STARTED";
export const PROMOTE_USER_SUCCESS = "PROMOTE_USER_SUCCESS";
export const PROMOTE_USER_FAILURE = "PROMOTE_USER_FAILURE";
export const REMOVE_INVITATION_STARTED = "REMOVE_INVITATION_STARTED";
export const REMOVE_INVITATION_SUCCESS = "REMOVE_INVITATION_SUCCESS";
export const REMOVE_INVITATION_FAILURE = "REMOVE_INVITATION_FAILURE";
export const LEAVE_TEAM_STARTED = "LEAVE_TEAM_STARTED";
export const LEAVE_TEAM_SUCCESS = "LEAVE_TEAM_SUCCESS";
export const LEAVE_TEAM_FAILURE = "LEAVE_TEAM_FAILURE";

// notes 
export const GET_NOTES_STARTED = "GET_NOTES_STARTED";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";
export const CREATE_NOTE_STARTED = "CREATE_NOTE_STARTED";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAILURE = "CREATE_NOTE_FAILURE";
export const CREATE_NOTE_SUCCESS_UPDATE_TEAM = "CREATE_NOTE_SUCCESS_UPDATE_TEAM";
export const DELETE_NOTE_STARTED = "DELETE_NOTE_STARTED";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILURE";
export const EDIT_NOTE_STARTED = "EDIT_NOTE_STARTED";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_FAILURE = "EDIT_NOTE_FAILURE";

// teams
export const GET_TEAMS_STARTED = "GET_TEAMS_STARTED";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAILURE = "GET_TEAMS_FAILURE";
export const GET_TEAMS_EXIST = "GET_TEAMS_EXIST";
export const CREATE_TEAM_STARTED = "CREATE_TEAM_STARTED";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILURE = "CREATE_TEAM_FAILURE";
export const DELETE_TEAM_STARTED = "DELETE_TEAM_STARTED";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILURE = "DELETE_TEAM_FAILURE";
export const EDIT_TEAM_STARTED = "EDIT_TEAM_STARTED";
export const EDIT_TEAM_SUCCESS = "EDIT_TEAM_SUCCESS";
export const EDIT_TEAM_FAILURE = "EDIT_TEAM_FAILURE";
